//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalaryPayment
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SalaryDBEntities : DbContext
    {
        public SalaryDBEntities()
            : base("name=SalaryDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblDeduction> tblDeduction { get; set; }
        public virtual DbSet<tblInfo> tblInfo { get; set; }
        public virtual DbSet<tblJobs> tblJobs { get; set; }
        public virtual DbSet<tblPerson> tblPerson { get; set; }
        public virtual DbSet<tblPersonGroup> tblPersonGroup { get; set; }
        public virtual DbSet<tblSalary> tblSalary { get; set; }
        public virtual DbSet<tblSalary_Deduction> tblSalary_Deduction { get; set; }
        public virtual DbSet<tblSalary_SalaryGroup> tblSalary_SalaryGroup { get; set; }
        public virtual DbSet<tblSalaryGroup> tblSalaryGroup { get; set; }
        public virtual DbSet<tblUser> tblUser { get; set; }
        public virtual DbSet<tblVam> tblVam { get; set; }
        public virtual DbSet<View_Person> View_Person { get; set; }
        public virtual DbSet<View_Salary> View_Salary { get; set; }
        public virtual DbSet<View_User> View_User { get; set; }
        public virtual DbSet<View_Vam> View_Vam { get; set; }
    }
}
