//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalaryPayment
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSalary_SalaryGroup
    {
        public Nullable<int> SalaryId { get; set; }
        public Nullable<int> IdSalaryGroup { get; set; }
        public string SalaryGroup { get; set; }
        public Nullable<long> BasePrice { get; set; }
        public int id { get; set; }
    }
}
