//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalaryPayment
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string CodeM { get; set; }
        public Nullable<int> Users { get; set; }
        public Nullable<int> BK { get; set; }
        public Nullable<int> RS { get; set; }
        public Nullable<int> Info { get; set; }
        public Nullable<int> PersonGroup { get; set; }
        public Nullable<int> Person { get; set; }
        public Nullable<int> Jobs { get; set; }
        public Nullable<int> SalaryGroup { get; set; }
        public Nullable<int> Deduction { get; set; }
        public Nullable<int> Salary { get; set; }
        public Nullable<int> Vam { get; set; }
        public int id { get; set; }
    }
}
