//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalaryPayment
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Person
    {
        public string FName { get; set; }
        public string LName { get; set; }
        public string Father { get; set; }
        public string CodeM { get; set; }
        public string ShSh { get; set; }
        public string BrDate { get; set; }
        public string Jensiyat { get; set; }
        public string Taahol { get; set; }
        public Nullable<int> ChildNum { get; set; }
        public Nullable<int> GroupId { get; set; }
        public string PersonGroup { get; set; }
        public string Sarbazi { get; set; }
        public string Tel { get; set; }
        public string Mobile { get; set; }
        public string Tahsilat { get; set; }
        public string Reshteh { get; set; }
        public string Address { get; set; }
        public int CodeP { get; set; }
        public Nullable<int> JobsId { get; set; }
        public string JobName { get; set; }
        public string Bemeh { get; set; }
        public string DateReg { get; set; }
        public string TypeReg { get; set; }
        public string ShHesab { get; set; }
        public string ShCard { get; set; }
        public string Shaba { get; set; }
        public string Bank { get; set; }
    }
}
