//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalaryPayment
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Vam
    {
        public int IdVam { get; set; }
        public Nullable<int> CodeP { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public string DateReg { get; set; }
        public string StartDate { get; set; }
        public Nullable<int> NumAgsat { get; set; }
        public Nullable<long> Price { get; set; }
        public Nullable<long> PriceAgsat { get; set; }
        public Nullable<long> Remainig { get; set; }
    }
}
