//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalaryPayment
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Salary
    {
        public int SalaryId { get; set; }
        public string DateReg { get; set; }
        public string Month { get; set; }
        public Nullable<int> CodeP { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public Nullable<int> ChildNum { get; set; }
        public Nullable<int> JobsId { get; set; }
        public string JobName { get; set; }
        public Nullable<int> OverTime { get; set; }
        public Nullable<long> OverTimePrice { get; set; }
        public Nullable<int> WorkDeduction { get; set; }
        public Nullable<long> WorkDeductionPrice { get; set; }
        public Nullable<int> Mission { get; set; }
        public Nullable<long> MissionPrice { get; set; }
        public Nullable<int> OverDay { get; set; }
        public Nullable<long> OverDayPrice { get; set; }
        public Nullable<int> DeductionDay { get; set; }
        public Nullable<long> DeductionDayPrice { get; set; }
        public Nullable<long> HelpPrice { get; set; }
        public Nullable<long> GestPrice { get; set; }
        public Nullable<long> DefDeductoinPrice { get; set; }
        public Nullable<long> DefSalaryPrice { get; set; }
        public Nullable<int> WorkDay { get; set; }
        public Nullable<int> WorkTime { get; set; }
        public Nullable<long> Bemeh { get; set; }
        public Nullable<long> TaxPrice { get; set; }
        public Nullable<long> SumSalary { get; set; }
        public Nullable<long> SumDeduction { get; set; }
        public Nullable<long> BaseSalary { get; set; }
        public Nullable<long> SalaryPrice { get; set; }
        public string Des { get; set; }
    }
}
